"""empty message

Revision ID: 7700f2ff1fcf
Revises: c1360da814e2
Create Date: 2025-11-25 00:44:37.278994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7700f2ff1fcf'
down_revision: Union[str, Sequence[str], None] = 'c1360da814e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_selected_models', sa.Column('editing_models', sa.String(), nullable=True))
    op.add_column('user_selected_models', sa.Column('other_models', sa.String(), nullable=True))
    op.add_column('user_selected_models', sa.Column('embends_models', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_selected_models', 'embends_models')
    op.drop_column('user_selected_models', 'other_models')
    op.drop_column('user_selected_models', 'editing_models')
    # ### end Alembic commands ###
