"""empty message

Revision ID: c1360da814e2
Revises: c150005a6a9a
Create Date: 2025-11-25 00:22:16.514481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1360da814e2'
down_revision: Union[str, Sequence[str], None] = 'c150005a6a9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_selected_models', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_selected_models', type_='unique')
    # ### end Alembic commands ###
