"""empty message

Revision ID: c150005a6a9a
Revises: 5e54b2e93a4c
Create Date: 2025-11-25 00:14:57.210089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c150005a6a9a'
down_revision: Union[str, Sequence[str], None] = '5e54b2e93a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_selected_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text_models', sa.String(), nullable=True),
    sa.Column('audio_models', sa.String(), nullable=True),
    sa.Column('video_models', sa.String(), nullable=True),
    sa.Column('image_models', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_selected_models')
    # ### end Alembic commands ###
